# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0758789019b05ebc2cb5b59516a17dc639e7fd939384092e89ff2305b99588041987c58544be2996af9cbaa77f33e2830f4b3022e885b68b9488b7f0586951dd

test:
  secret_key_base: efde3535f37cf35816019e3feb037a029b53c6e27151ddd86409377cc20f940c71abd42d696d8d8b0fb577cc8438310103515270a665bfd9281dff257776c84b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
